input {
  file {
    path => "/var/log/app/api.log"
    start_position => "beginning"
    codec => "json"
  }
}

filter {
  # Add any custom filters here if necessary
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "k8s-failure-prediction-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
